spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.116.137:1521:XE
    username: dmcJpa
    password: dmcJpa
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1060034576462-kflrrd6srvmrd5cqctq8ts957gmk0748.apps.googleusercontent.com
            client-secret: gSz_vlx-vSscf1VlAJoMTp-z
            scope: profile,email

#        naver:
#          client-id: WedWxpZ5XN8jrrX8Qpul
#          client-secret: 9zf8pzwEKD
#          redirect-uri: {baseUrl}/{action}/oauth2/code/{registrationId}
#          authorization-grant-type: authorization_code
#          scope: name,email,profile_image
#          client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response



  profiles:
    include: oauth,real-db

  session:
    store-type: jdbc




logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace