spring:
  datasource:    url: jdbc:oracle:thin:@172.30.1.48:1521:XE
    username: dmcJpa
    password: dmcJpa
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace